name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase db start

      - name: Verify generated types
        run: |
          supabase gen types typescript --local > ./src/types/database.types.ts

          if git diff --ignore-space-at-eol --exit-code --quiet ./src/types/database.types.ts; then
            echo "✓ Types are up to date"
          else
            echo "❌ Generated types differ from committed version!"
            echo "   Run: supabase gen types typescript --local > ./src/types/database.types.ts"
            git diff ./src/types/database.types.ts
            exit 1
          fi
