name: Automated Tests

on: pull_request

jobs:
  vitest:
    name: vitest ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-node-version
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}
      - run: npm ci
      - run: npm test
